// board state
export const SET_DEMO = 'SET_DEMO';
export const DELETE_ALL_BOARDS = 'DELETE_ALL_BOARDS';
export const SET_BOARDS = 'SET_BOARDS';
export const ADD_BOARD = 'ADD_BOARD';
export const SET_TITLE = 'SET_TITLE';
export const SET_DESCRIBTION = 'SET_DESCRIBTION';
export const SET_COLOR = 'SET_COLOR';
export const ADD_LIST = 'ADD_LIST';
export const SET_LIST_TITLE = 'SET_LIST_TITLE';
export const ADD_CARD = 'ADD_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const MOVE_CARD = 'MOVE_CARD';
export const SET_LABELS = 'SET_LABELS';

// alert state
export const SET_ALERT = 'SET_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

// user state
export const SET_CURRENT_BOARD_ID = 'SET_CURRENT_BOARD_ID';
export const CLEAR_CURRENT_BOARD_ID = 'CLEAR_CURRENT_BOARD_ID';
export const SET_CURRENT_LIST_ID = 'SET_CURRENT_LIST_ID';
export const CLEAR_CURRENT_LIST_ID = 'CLEAR_CURRENT_LIST_ID';
export const SET_MODAL = 'SET_MODAL';
export const SET_MODAL_TYPE = 'SET_MODAL_TYPE';
export const SET_OPTIONS_MODAL = 'SET_OPTIONS_MODAL';
export const SET_OPTIONS_MODAL_TYPE = 'SET_OPTIONS_MODAL_TYPE';
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const CLEAR_CURRENT_CARD = 'CLEAR_CURRENT_CARD';
export const SET_MOUSE_POS = 'S`ET_MOUSE_POS';
export const SET_BIG_LABELS = 'SET_BIG_LABELS';
export const SET_OPTIONS_MODAL_STEP = 'SET_OPTIONS_MODAL_STEP';
export const SET_OPTIONS_MODAL_STEP_TYPE = 'SET_OPTIONS_MODAL_STEP_TYPE';
export const SET_OPTIONS_MODAL_STEP_DATA = 'SET_OPTIONS_MODAL_STEP_DATA';
export const SET_DATA = 'SET_DATA';
export const SET_SHOW_MENU = 'SET_SHOW_MENU';
export const TOGGLE_SHOW_BOARDS = 'TOGGLE_SHOW_BOARDS';
export const SET_KEEP_BOARDS = 'SET_KEEP_BOARDS';
export const SET_FOUND_CARD_ID = 'SET_FOUND_CARD_ID';
